package ru.tinkoff.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import ru.tinkoff.helpers.DriverUtils;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Открытие сайта")
    void generatedTest() {
        step("Открыть 'https://www.tinkoff.ru/'", () -> step("// todo: just add selenium action"));
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.tinkoff.ru/'", () ->
                open("https://www.tinkoff.ru/"));

        step("Page title should have text 'Тинькофф — Кредитные и дебетовые карты, кредиты для бизнеса и физических лиц'", () -> {
            String expectedTitle = "Тинькофф — Кредитные и дебетовые карты, кредиты для бизнеса и физических лиц";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.tinkoff.ru/'", () ->
                open("https://www.tinkoff.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}
