package ru.tinkoff.tests;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import ru.tinkoff.tests.pages.HomePage;
import ru.tinkoff.tests.pages.InvestmentPage;


public class TinkoffTests extends TestBase {

    @Test
    @DisplayName("Проверка недоступности клика по кнопке 'Открыть счёт' без ввода данных")
    void checkTheButtonOpenAnAccount() {
        // Arrange
        HomePage homePage = new HomePage();
        homePage.openMainPage();
        // Act
        homePage.pressTheButtonInvestments();
        // Assert
        InvestmentPage investmentPage = new InvestmentPage();
        investmentPage.checkTheButtonOpenAnAccountDisabled();
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.tinkoff.ru/'", () ->
                open("https://www.tinkoff.ru/"));

        step("Page title should have text 'Тинькофф — Кредитные и дебетовые карты, кредиты для бизнеса и физических лиц'", () -> {
            String expectedTitle = "Тинькофф — Кредитные и дебетовые карты, кредиты для бизнеса и физических лиц";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.tinkoff.ru/'", () ->
                open("https://www.tinkoff.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}
